name: Keep Supabase Alive

on:
  schedule:
    # S'exécute tous les 3 jours à minuit
    - cron: '0 0 */3 * *'
  workflow_dispatch: # Permet de lancer la tâche manuellement si besoin

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send Ping to Supabase
        run: |
          curl -X GET "${{ secrets.https://kjhrikutzxixmvmhbjqk.supabase.co }}/rest/v1/" \
            -H "apikey: ${{ secrets.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqaHJpa3V0enhpeG12bWhianFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyNzg4NzQsImV4cCI6MjA4Njg1NDg3NH0.df9_4U08BN-NPNaXYXsyWTkSZqoNT7UtF_Iz8lx6HZo }}" \
            -H "Authorization: Bearer ${{ secrets.eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqaHJpa3V0enhpeG12bWhianFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzEyNzg4NzQsImV4cCI6MjA4Njg1NDg3NH0.df9_4U08BN-NPNaXYXsyWTkSZqoNT7UtF_Iz8lx6HZo }}"
